name: Terraform CI/CD pipeline

on: 
  push:
    branches:
      - awsdev/task-2

    pull_request: 
      branches:
        - awsdev/task-2 # run when had pr on this branch

jobs: 
  terraform:
    name: Terraform Job
    runs-on: ubuntu-latest
    steps:
      # Step 1: check code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: configure credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: latest

      # Step 4:
      - name: Terraform Init
        run: terraform init

      # Step 5:
      - name: Terraform Plan
        run: terraform plan

      # Step 6:
      - name: Terraform Apply
        run: terraform apply -auto-approve

